FROM mysql:8.0
COPY ../../../docker/mysql/dbdata /var/lib/mysql/
COPY ../../../docker/mysql/my.cnf /etc/mysql/my.cnf
COPY ../../../docker/mysql/mysql-files /var/lib/mysql-files
#            - dbdata:/var/lib/mysql/
#            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
#            - ./docker/mysql/mysql-files:/var/lib/mysql-files



