version: '3.7'
services:

    #PHP Service
    app:
        build:
            context: .
            dockerfile: docker/Dockerfiles/php/Dockerfile
        image: 9wimu9/auth-app-php
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - docker_app_network

    #Nginx Service
    webserver:
        image: 9wimu9/auth-app-webserver
        build:
            context: .
            dockerfile: docker/Dockerfiles/nginx/Dockerfile
        container_name: docker_app_webserver
        restart: unless-stopped
        tty: true
        ports:
            - "8113:80"
            - "445:443"
        volumes:
            - ./:/var/www
        networks:
            - docker_app_network
        depends_on:
            - app

    #MySQL Service
    db:
        image: 9wimu9/auth-app-db
        build:
            context: .
            dockerfile: docker/Dockerfiles/mysql/Dockerfile
        container_name: docker_app_mysql_server
        restart: unless-stopped
        tty: true
        ports:
            - "3318:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
        networks:
            - docker_app_network
        depends_on:
            - app
#Docker Networks
networks:
    docker_app_network:
        driver: bridge
#Volumes
volumes:
    dbdata:
        driver: local
# docker-compose down -v && docker-compose up -d
