version: '2.1'

services:
  mariadb:
    build:
      context: .
      dockerfile: Dockerfiles/mariadb/Dockerfile
    image: 9wimu9/auth-api-mariadb2:latest
    environment:
      MARIADB_ROOT_PASSWORD: root
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
    ports:
      - '3306:3306'

  myapp:
    build:
      context: .
      dockerfile: Dockerfiles/php/Dockerfile
    image: 9wimu9/auth-api-myapp2:latest
    ports:
      - '8000:8000'
#    volumes:
#      - './:/app'
    depends_on:
      - mariadb

#auth-LoadB-1FRA2XQ42LLW-82543b575d8e49f3.elb.us-east-1.amazonaws.com:8000
#auth-LoadB-1FRA2XQ42LLW-82543b575d8e49f3.elb.us-east-1.amazonaws.com:3306
#        #https://github.com/aws/aws-cli/issues/6242#issuecomment-1079214960
#      aws ecs update-service --cluster auth-api --service auth-api-MyappService-3XxKnaCQnelw --region us-east-1 --enable-execute-command --force-new-deployment
#    aws ecs execute-command  \
#    --region us-east-1 \
#    --cluster auth-api \
#    --task 9513918830e145ad8a02ce48e9c09fe5 \
#    --container  myapp \
#    --command "/bin/bash" \
#    --interactive
#
#    aws ecs run-task --cluster auth-api --task-definition auth-api-myapp:7

