version: '3.7'
services:

    #PHP Service
    app:
        build:
            context: .
            dockerfile: docker/Dockerfiles/php/Dockerfile
        image: 9wimu9/php
        container_name: docker_app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: docker_app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - docker_app_network

    #Nginx Service
    webserver:
        image: 9wimu9/nginx
        container_name: docker_app_webserver
        restart: unless-stopped
        tty: true
        ports:
            - "8113:80"
            - "445:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - docker_app_network

    #MySQL Service
    db:
        image: 9wimu9/mysql
        container_name: docker_app_mysql_server
        restart: unless-stopped
        tty: true
        ports:
            - "3318:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - dbdata:/var/lib/mysql/
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
            - ./docker/mysql/mysql-files:/var/lib/mysql-files
        networks:
            - docker_app_network

#Docker Networks
networks:
    docker_app_network:
        driver: bridge
#Volumes
volumes:
    dbdata:
        driver: local
# docker-compose down -v && docker-compose up -d
